name: Engine Release
on:
  push:
    tags: ['v*']

env:
  CI: true
  WORKING_DIRECTORY: '.'

concurrency:
  group: ${{github.workflow}}-${{github.head_ref}}
  cancel-in-progress: false

jobs:
  # Avoid failing releases when the pnpm-lock.yaml was not updated
  check-pnpm:
    name: Check PNPM lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/node
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
          repo-token: ${{ secrets.GIT_TOKEN }}

      - run: pnpm i --frozen-lockfile --ignore-scripts

  goreleaser-linux:
    name: Release Linux build
    runs-on: 'ubuntu-latest'
    needs:
      - check-pnpm
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/go
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GIT_TOKEN }}

      - name: go env
        run: go env

      - name: generate go types based on protobuf definitions
        run: make codegen-go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          workdir: './cmd/wunderctl'
          args: release --rm-dist --config ./../../.github/goreleaser/.goreleaser-linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          GH_AUTH_DEMO_CLIENT_ID: ${{ secrets.GH_AUTH_DEMO_CLIENT_ID }}
          GH_AUTH_DEMO_CLIENT_SECRET: ${{ secrets.GH_AUTH_DEMO_CLIENT_SECRET }}
